name: Build

on:
  push:
    branches:
      - "**"
  pull_request:


jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
      shell: cmd
    - name: build-bundle
      run: |
        pyinstaller --onefile main.py
        move dist\main.exe .
      shell: cmd
    - name: Download streamlink
      run: |
        curl -L -o streamlink.zip https://github.com/streamlink/windows-builds/releases/download/6.0.0-1/streamlink-6.0.0-1-py311-x86_64.zip
        7z x streamlink.zip
        move streamlink-6.0.0-1-py311-x86_64 streamlink
      shell: cmd
    - name: Tweaking streamlink parameter
      run: |
        cd streamlink\pkgs\streamlink\stream
        curl -L -o sed.exe https://github.com/mbuilov/sed-windows/raw/master/sed-4.9-x86.exe
        sed.exe "s/SEGMENT_QUEUE_TIMING_THRESHOLD_FACTOR = 2/SEGMENT_QUEUE_TIMING_THRESHOLD_FACTOR = 6/" hls.py > hls_mod.py
        move /y hls_mod.py hls.py
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: Sister-Recorder-windows
        path: |
          main.exe
          config.example.ini
          streamlink/

